version: "3.8"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
#      - VERSION=docker
#      - UMASK_SET=022 #optional
#      - PLEX_CLAIM= #optional
    volumes:
      - ${mount_point}/plexconfig:/config
      - ${mount_point}/plextv:/tv
      - ${mount_point}/plexmovies:/movies
      - ${mount_point}/downloads:/transdownloads
    restart: unless-stopped
