version: "3.8"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge        # Required
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=${email}     # Required
      - PASS=${password}         # Required
      - CONNECT=United_Kingdom
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24 
    ports:
      - 8080:8080
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      
  transmission:
    image: linuxserver/transmission
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
#      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin
      - PASS=${torrent_password}
    volumes:
      - ${mount_point}/transconfig:/config
      - ${mount_point}/downloads:/downloads
      - ${mount_point}/transwatch:/watch
      - ${mount_point}/plextv:/plextv
      - ${mount_point}/plexmovies:/plexmovies
    restart: unless-stopped

# The torrent service will be available at https://localhost:9091/ from pi, or anywhere inside the local network http://192.168.1.xxx:9091
